package com.taskmasterAWSJava.Java401.taskmaster.LukeAWS;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName = "Taskmaster")
public class Task {
    private String id;
    private String title;
    private String description;
    private String status;
    @DynamoDBAttribute
    private String assignee;
    private String image;
    private String thumbnailImage;

    public String getThumbnailImage() {
        return thumbnailImage;
    }

    public void setThumbnailImage(String thumbnailImage) {
        this.thumbnailImage = thumbnailImage;
    }

    @DynamoDBAttribute
    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Task() {}

    public Task(String title, String description, String status, String assignee){
        this.title = title;
        this.description = description;
        this.status = status;
        this.assignee = assignee;
    }

    public Task(String title, String description, String status, String assignee, String image, String thumbnailImage){
        this(title, description, status, assignee);
        this.image = image;
        this.thumbnailImage = thumbnailImage;
    }

    public Task(String image, String thumbnailImage){
        this.image = image;
        this.thumbnailImage = thumbnailImage;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getAssignee() {
        return assignee;
    }

    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }
}


